var TrafficLight;
(function (TrafficLight) {
    TrafficLight["Red"] = "STOP";
    TrafficLight["Yellow"] = "WAIT";
    TrafficLight["Green"] = "GO";
})(TrafficLight || (TrafficLight = {}));
console.log(TrafficLight.Red);
console.log(TrafficLight.Yellow);
console.log(TrafficLight.Green);
// starter TypeScript file
var X;
X = ["hello", 10];
console.log(X);
var values = "Hello World";
console.log(values.length);
var test1 = { id: 1, name: "Test1", status: "passed" };
console.log(test1);
var test2 = { id: 2, name: "Test2" };
console.log(test2);
var user1 = { id: 1, name: "Test1", status: "passed" };
console.log(user1);
var user2 = { id: 2, name: "Test2" };
console.log(user2);
var studentid = { id: 5, name: "John" };
console.log(studentid);
studentid = { id: 6, name: "Doe" };
console.log(studentid);
var Name = "sanji";
var age = 21;
var address = "strawhat pirates";
console.log("My name is ".concat(Name, ". I am ").concat(age, " years old and live in ").concat(address, "."));
var data = undefined;
console.log(data);
var data1 = null;
console.log(data1);
var theater = ["krishnalaya", "pvr", "inox"];
console.log(theater[0]);
var passed = true;
console.log(passed);
